sudo: required
services: 
        - docker

before_install:
        - docker build -t rsilva25/docker-react2 -f Dockerfile.dev .

script:
        - docker run rsilva25/docker-react2 npm run test -- --coverage
